# Generated by Django 2.1.2 on 2018-10-13 12:21

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('news_type', models.CharField(choices=[('0', '通讯'), ('1', '通知')], default='0', max_length=16)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default='')),
                ('actor', models.ForeignKey(limit_choices_to={'is_admin': True}, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '动态',
            },
        ),
        migrations.CreateModel(
            name='NewsPhotos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='upload/%Y/%m/%d', verbose_name='图片（建议size为800*450）')),
                ('describe', models.TextField(verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(limit_choices_to={'is_admin': True}, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '轮播图',
            },
        ),
    ]
