# Generated by Django 2.1.3 on 2018-12-06 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '动态', 'verbose_name_plural': '动态'},
        ),
        migrations.AlterModelOptions(
            name='newsphotos',
            options={'verbose_name': '轮播图', 'verbose_name_plural': '轮播图'},
        ),
    ]
