# Generated by Django 2.1.2 on 2018-10-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game', models.CharField(default='', max_length=256)),
                ('date', models.DateField(verbose_name='比赛时间')),
                ('achievement', models.CharField(max_length=256, verbose_name='成就')),
                ('img', models.ImageField(upload_to='upload/%Y/%m/%d', verbose_name='比赛照片一张')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
