# Generated by Django 2.1.3 on 2018-11-13 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': '历程'},
        ),
    ]
