# Generated by Django 2.1.3 on 2018-12-03 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Team', '0002_auto_20181113_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game', models.CharField(default='', max_length=125, verbose_name='比赛名称')),
                ('result', models.CharField(default='', max_length=125, verbose_name='比赛结果')),
                ('game_time', models.DateTimeField(default=None, verbose_name='比赛时间')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '比赛记录',
                'db_table': 'GameRecord',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='队员')),
            ],
            options={
                'verbose_name': '队员信息',
                'db_table': 'TeamMember',
            },
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Team.TeamMember', verbose_name='队员'),
        ),
    ]
