# Generated by Django 2.1.3 on 2018-12-06 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0003_auto_20181203_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamerecord',
            options={'verbose_name': '比赛记录', 'verbose_name_plural': '比赛记录'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': '历程', 'verbose_name_plural': '历程'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': '队员信息', 'verbose_name_plural': '队员信息'},
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_record', to='Team.TeamMember', verbose_name='队员'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_member', to=settings.AUTH_USER_MODEL, verbose_name='队员'),
        ),
    ]
