# Generated by Django 2.1.2 on 2018-10-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='', max_length=256)),
                ('email', models.EmailField(max_length=256, verbose_name='email address')),
                ('phone', models.IntegerField()),
                ('major', models.CharField(default='', max_length=56, null=True)),
            ],
        ),
    ]
