# Generated by Django 2.1.2 on 2018-10-13 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0003_auto_20181013_2109'),
        ('Activity', '0002_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('headline', models.CharField(default='', max_length=256)),
                ('describe', models.TextField(default='', null=True)),
                ('game_time', models.DateTimeField()),
                ('start_enter_time', models.DateTimeField()),
                ('end_enter_time', models.DateTimeField()),
                ('actor', models.ForeignKey(limit_choices_to={'is_admin': True}, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_captain', models.BooleanField(default=False)),
                ('user_name', models.CharField(default='', max_length=256)),
                ('student_id', models.IntegerField()),
                ('email', models.EmailField(max_length=256, verbose_name='email address')),
                ('phone', models.IntegerField()),
                ('major', models.CharField(default='', max_length=56, null=True)),
                ('school', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='User.School')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(default='', max_length=256, null=True)),
                ('teacher', models.CharField(default='', max_length=256, null=True)),
                ('game', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Activity.Game')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Activity.Team'),
        ),
    ]
