# Generated by Django 2.1.2 on 2018-10-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0003_auto_20181013_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('0', '团队赛'), ('1', '个人赛')], default='0', max_length=16),
        ),
    ]
