# Generated by Django 2.1.2 on 2018-10-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0004_game_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='end_enter_time',
            field=models.DateTimeField(verbose_name='报名截止时间'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_time',
            field=models.DateTimeField(verbose_name='活动时间'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('0', '团队'), ('1', '个人')], default='0', max_length=16, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='game',
            name='headline',
            field=models.CharField(default='', max_length=256, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_enter_time',
            field=models.DateTimeField(verbose_name='报名开始时间'),
        ),
        migrations.AlterField(
            model_name='team',
            name='teacher',
            field=models.CharField(default=' ', max_length=256, null=True),
        ),
    ]
