# Generated by Django 2.1.2 on 2018-10-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0006_auto_20181016_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='game',
            name='img',
            field=models.ImageField(blank=True, default=None, upload_to='upload/QR/%Y/%m/%d', verbose_name='图片（建议size为100*100）'),
        ),
        migrations.AlterField(
            model_name='team',
            name='is_verify',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='通过审核'),
        ),
    ]
