# Generated by Django 2.1.2 on 2018-10-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0007_auto_20181017_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='locaton',
            field=models.CharField(default='', max_length=256, null=True),
        ),
    ]
