# Generated by Django 2.1.2 on 2018-10-18 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0008_game_locaton'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': '活动'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': '队伍/个人'},
        ),
        migrations.AddField(
            model_name='game',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='headline',
            field=models.CharField(default='', max_length=256, verbose_name='活动名称'),
        ),
        migrations.AlterField(
            model_name='game',
            name='locaton',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='活动地点'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=256, verbose_name='email asdaddress'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='队名/个人名称'),
        ),
    ]
