# Generated by Django 2.1.2 on 2018-10-18 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0009_auto_20181018_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='create_time',
        ),
    ]
