# Generated by Django 2.1.2 on 2018-10-18 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0011_game_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='create_time',
        ),
    ]
