# Generated by Django 2.1.2 on 2018-10-18 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0013_game_create_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='locaton',
            new_name='location',
        ),
    ]
