# Generated by Django 2.1.2 on 2018-10-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0014_auto_20181018_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='is_verify',
            field=models.BooleanField(blank=True, default=False, verbose_name='通过审核'),
        ),
    ]
