# Generated by Django 2.1.4 on 2018-12-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0016_auto_20181206_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='student_id',
            field=models.BigIntegerField(),
        ),
    ]
