# Generated by Django 2.1.3 on 2018-12-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codePool', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name': '码池', 'verbose_name_plural': '码池'},
        ),
        migrations.AlterField(
            model_name='code',
            name='is_share',
            field=models.BooleanField(default=False, verbose_name='是否分享'),
        ),
        migrations.AlterModelTable(
            name='code',
            table='Code',
        ),
    ]
