# Generated by Django 2.1.2 on 2018-10-16 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20181015_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': '学校'},
        ),
    ]
