# Generated by Django 2.1.3 on 2018-11-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20181016_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='real_name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
