# Generated by Django 2.1.3 on 2018-12-06 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20181203_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': '学校', 'verbose_name_plural': '学校'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='邮箱地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.IntegerField(blank=True, default=2018, null=True, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.CharField(blank=True, default='', max_length=125, null=True, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='User.School', verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='用户账号'),
        ),
    ]
