# Generated by Django 2.1.4 on 2018-12-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_auto_20181217_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
